## Search song in Spotify and id

In [1]:
import spotipy # install if needed
from spotipy.oauth2 import SpotifyClientCredentials
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from bs4 import BeautifulSoup
import requests 
from random import randint


In [2]:
import getpass
client_id=str(getpass.getpass('client_id?'))
client_secret=str(getpass.getpass('client_secret?'))

client_id?········
client_secret?········


In [3]:
sp = spotipy.Spotify(auth_manager=SpotifyClientCredentials(client_id=client_id, client_secret=client_secret))

In [4]:
song=input('Enter a song do you like?').lower()


Enter a song do you like?la bamba


In [6]:
results = sp.search(q=song, limit=1)

In [7]:
id=results["tracks"]['items'][0]['id']
id

'2aEeghgUcnu75tzcolFMfs'

In [8]:
songf=sp.audio_features(id)
songf

[{'danceability': 0.516,
  'energy': 0.809,
  'key': 0,
  'loudness': -6.419,
  'mode': 1,
  'speechiness': 0.0545,
  'acousticness': 0.787,
  'instrumentalness': 0.000331,
  'liveness': 0.303,
  'valence': 0.939,
  'tempo': 75.099,
  'type': 'audio_features',
  'id': '2aEeghgUcnu75tzcolFMfs',
  'uri': 'spotify:track:2aEeghgUcnu75tzcolFMfs',
  'track_href': 'https://api.spotify.com/v1/tracks/2aEeghgUcnu75tzcolFMfs',
  'analysis_url': 'https://api.spotify.com/v1/audio-analysis/2aEeghgUcnu75tzcolFMfs',
  'duration_ms': 126960,
  'time_signature': 4}]

In [9]:
results["tracks"]

{'href': 'https://api.spotify.com/v1/search?query=la+bamba&type=track&offset=0&limit=1',
 'items': [{'album': {'album_type': 'album',
    'artists': [{'external_urls': {'spotify': 'https://open.spotify.com/artist/5Y9xEAGW4GwGJgbiI6W85P'},
      'href': 'https://api.spotify.com/v1/artists/5Y9xEAGW4GwGJgbiI6W85P',
      'id': '5Y9xEAGW4GwGJgbiI6W85P',
      'name': 'Ritchie Valens',
      'type': 'artist',
      'uri': 'spotify:artist:5Y9xEAGW4GwGJgbiI6W85P'}],
    'available_markets': ['AD',
     'AE',
     'AG',
     'AL',
     'AM',
     'AO',
     'AR',
     'AT',
     'AU',
     'AZ',
     'BA',
     'BB',
     'BD',
     'BE',
     'BF',
     'BG',
     'BH',
     'BI',
     'BJ',
     'BN',
     'BO',
     'BR',
     'BS',
     'BT',
     'BW',
     'BY',
     'BZ',
     'CA',
     'CH',
     'CI',
     'CL',
     'CM',
     'CO',
     'CR',
     'CV',
     'CW',
     'CY',
     'CZ',
     'DE',
     'DJ',
     'DK',
     'DM',
     'DO',
     'DZ',
     'EC',
     'EE',
     'EG'

In [10]:
songf=pd.DataFrame(songf)

In [11]:
songf.head()

danceability  energy  key  loudness  mode  speechiness  acousticness  \
0         0.516   0.809    0    -6.419     1       0.0545         0.787   

   instrumentalness  liveness  valence   tempo            type  \
0          0.000331     0.303    0.939  75.099  audio_features   

                       id                                   uri  \
0  2aEeghgUcnu75tzcolFMfs  spotify:track:2aEeghgUcnu75tzcolFMfs   

                                          track_href  \
0  https://api.spotify.com/v1/tracks/2aEeghgUcnu7...   

                                        analysis_url  duration_ms  \
0  https://api.spotify.com/v1/audio-analysis/2aEe...       126960   

   time_signature  
0               4

In [12]:
sf_cl=songf.drop(['type','uri','track_href','analysis_url','id'],axis=1)

In [13]:
sf_cl.head()

danceability  energy  key  loudness  mode  speechiness  acousticness  \
0         0.516   0.809    0    -6.419     1       0.0545         0.787   

   instrumentalness  liveness  valence   tempo  duration_ms  time_signature  
0          0.000331     0.303    0.939  75.099       126960               4

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler= StandardScaler()

In [16]:
scaler.fit(sf_cl)

StandardScaler()

In [17]:
sf_cl_sc=scaler.transform(sf_cl)

In [18]:
sf_cl_sc

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
from sklearn.cluster import KMeans

#define the model, fit the model to your data 

kmeans = KMeans(n_clusters=1, random_state=40)
kmeans.fit(sf_cl_sc)

C:\ProgramData\Anaconda3\envs\Ironhack_env\lib\site-packages\sklearn\cluster\_kmeans.py:881: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=1.
  warnings.warn(


KMeans(n_clusters=1, random_state=40)

In [20]:
kmeans.cluster_centers_

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [21]:
cluster=kmeans.predict(sf_cl_sc)

In [22]:
cluster

array([0])

In [23]:
cluster=cluster[0]

In [24]:
cluster

0

## Clustering Data

In [25]:
fs=pd.read_csv('film_series.csv')

In [26]:
fs.head()

Song  \
0                                           Our Town   
1                                       Married Life   
2     Reflection - From "Mulan" / Soundtrack Version   
3  Colors of the Wind - From "Pocahontas" / Sound...   
4  Ma Belle Evangeline - From "The Princess and t...   

                                        Movie  \
0  Cars Original Soundtrack (English Version)   
1     Up (Original Motion Picture Soundtrack)   
2                                       Mulan   
3                                  Pocahontas   
4                   The Princess and the Frog   

                                                Link                      id  \
0  https://api.spotify.com/v1/tracks/1ENnpCRfGWQL...  1ENnpCRfGWQLVGL9pEyVao   
1  https://api.spotify.com/v1/tracks/7iocNjLrxPHL...  7iocNjLrxPHLl8njgRlv5U   
2  https://api.spotify.com/v1/tracks/2AILbz83cBnr...  2AILbz83cBnrAMAG06rZts   
3  https://api.spotify.com/v1/tracks/1OYOLWqKmhkF...  1OYOLWqKmhkFIx2KC9ek1a   
4  https://api.spotify.com/v1/tracks/2P8QqrZ42YNP...  2P8QqrZ42YNP8Ao5uRMLO0   

   danceability  energy  key  loudness  mode  speechiness  acousticness  \
0         0.491  0.2720    2   -11.627     1       0.0283         0.874   
1         0.278  0.0675    0   -20.946     1       0.0400         0.970   
2         0.255  0.1740    9   -19.217     1       0.0379         0.805   
3         0.272  0.1640    1   -17.040     1       0.0460         0.929   
4         0.378  0.3520    3    -8.745     1       0.0354         0.812   

   instrumentalness  liveness  valence    tempo  \
0          0.000563    0.1270   0.1010  111.642   
1          0.732000    0.0812   0.1120   82.626   
2          0.009110    0.3350   0.0829   80.707   
3          0.001100    0.1090   0.2280   81.551   
4          0.000005    0.1060   0.3060  139.491   

                                    uri  \
0  spotify:track:1ENnpCRfGWQLVGL9pEyVao   
1  spotify:track:7iocNjLrxPHLl8njgRlv5U   
2  spotify:track:2AILbz83cBnrAMAG06rZts   
3  spotify:track:1OYOLWqKmhkFIx2KC9ek1a   
4  spotify:track:2P8QqrZ42YNP8Ao5uRMLO0   

                                          track_href  \
0  https://api.spotify.com/v1/tracks/1ENnpCRfGWQL...   
1  https://api.spotify.com/v1/tracks/7iocNjLrxPHL...   
2  https://api.spotify.com/v1/tracks/2AILbz83cBnr...   
3  https://api.spotify.com/v1/tracks/1OYOLWqKmhkF...   
4  https://api.spotify.com/v1/tracks/2P8QqrZ42YNP...   

                                        analysis_url  duration_ms  \
0  https://api.spotify.com/v1/audio-analysis/1ENn...       247385   
1  https://api.spotify.com/v1/audio-analysis/7ioc...       250573   
2  https://api.spotify.com/v1/audio-analysis/2AIL...       146760   
3  https://api.spotify.com/v1/audio-analysis/1OYO...       214400   
4  https://api.spotify.com/v1/audio-analysis/2P8Q...       115693   

   time_signature  
0               4  
1               3  
2               4  
3               3  
4               5

In [27]:
fscl=fs.drop(['Song','Movie','Link','uri','track_href','analysis_url','id'],axis=1)

In [28]:
scaler.fit(fscl)

StandardScaler()

In [29]:
fscl_scl=scaler.transform(fscl)

In [30]:
from sklearn.cluster import KMeans

#define the model, fit the model to your data 

kmeans = KMeans(n_clusters=50, random_state=40)
kmeans.fit(fscl_scl)

KMeans(n_clusters=50, random_state=40)

In [31]:
kmeans.cluster_centers_

array([[ 5.65074621e-01, -1.98767263e-01,  4.91914094e-01,
         2.94268069e-02,  1.83872690e-01,  3.66201685e+00,
         5.69675299e-01, -5.09009284e-01, -7.35487942e-03,
         2.03469930e-01, -4.53762960e-01,  1.31037763e+00,
         1.95881854e-01],
       [-4.29517327e-01, -1.03684015e+00, -1.11788270e+00,
        -8.06497675e-01,  6.54763470e-01, -2.60937098e-01,
         9.12257804e-01, -6.43494755e-01, -2.06778098e-01,
        -4.86593262e-01, -4.60019863e-01, -1.71452131e-01,
         5.60201324e-01],
       [ 1.37617985e+00,  1.22232742e+00,  4.50911689e-01,
         8.57867688e-01, -1.48323970e+00,  1.53693627e-02,
        -1.16190377e+00, -6.34421550e-01, -2.00205317e-01,
         1.43139955e+00, -1.12832572e-02,  1.76655260e-01,
         3.21054387e-01],
       [ 2.51399797e-01, -7.23012913e-02,  1.01301706e+00,
         2.55919521e-01, -1.48323970e+00, -1.25833137e-01,
         3.74523994e-01, -5.10606524e-01, -3.41322574e-01,
        -2.05480851e-01,  5.60076087e

In [32]:
clusters=kmeans.predict(fscl_scl)

In [33]:
pd.Series(clusters).value_counts().sort_index()

0      22
1     111
2     151
3      76
4      59
5      35
6     202
7     135
8      74
9      64
10    123
11     72
12    100
13     85
14     88
15     92
16     19
17     71
18    114
19     45
20     64
21     21
22     34
23     41
24     65
25     60
26     84
27     36
28     88
29     77
30     36
31      5
32     52
33    115
34     32
35     58
36     73
37     52
38     95
39     84
40    110
41     38
42     91
43    109
44     75
45     51
46     60
47     53
48     87
49     64
dtype: int64

In [34]:
fs['Clusters']=clusters
fs.head()

Song  \
0                                           Our Town   
1                                       Married Life   
2     Reflection - From "Mulan" / Soundtrack Version   
3  Colors of the Wind - From "Pocahontas" / Sound...   
4  Ma Belle Evangeline - From "The Princess and t...   

                                        Movie  \
0  Cars Original Soundtrack (English Version)   
1     Up (Original Motion Picture Soundtrack)   
2                                       Mulan   
3                                  Pocahontas   
4                   The Princess and the Frog   

                                                Link                      id  \
0  https://api.spotify.com/v1/tracks/1ENnpCRfGWQL...  1ENnpCRfGWQLVGL9pEyVao   
1  https://api.spotify.com/v1/tracks/7iocNjLrxPHL...  7iocNjLrxPHLl8njgRlv5U   
2  https://api.spotify.com/v1/tracks/2AILbz83cBnr...  2AILbz83cBnrAMAG06rZts   
3  https://api.spotify.com/v1/tracks/1OYOLWqKmhkF...  1OYOLWqKmhkFIx2KC9ek1a   
4  https://api.spotify.com/v1/tracks/2P8QqrZ42YNP...  2P8QqrZ42YNP8Ao5uRMLO0   

   danceability  energy  key  loudness  mode  speechiness  ...  \
0         0.491  0.2720    2   -11.627     1       0.0283  ...   
1         0.278  0.0675    0   -20.946     1       0.0400  ...   
2         0.255  0.1740    9   -19.217     1       0.0379  ...   
3         0.272  0.1640    1   -17.040     1       0.0460  ...   
4         0.378  0.3520    3    -8.745     1       0.0354  ...   

   instrumentalness  liveness  valence    tempo  \
0          0.000563    0.1270   0.1010  111.642   
1          0.732000    0.0812   0.1120   82.626   
2          0.009110    0.3350   0.0829   80.707   
3          0.001100    0.1090   0.2280   81.551   
4          0.000005    0.1060   0.3060  139.491   

                                    uri  \
0  spotify:track:1ENnpCRfGWQLVGL9pEyVao   
1  spotify:track:7iocNjLrxPHLl8njgRlv5U   
2  spotify:track:2AILbz83cBnrAMAG06rZts   
3  spotify:track:1OYOLWqKmhkFIx2KC9ek1a   
4  spotify:track:2P8QqrZ42YNP8Ao5uRMLO0   

                                          track_href  \
0  https://api.spotify.com/v1/tracks/1ENnpCRfGWQL...   
1  https://api.spotify.com/v1/tracks/7iocNjLrxPHL...   
2  https://api.spotify.com/v1/tracks/2AILbz83cBnr...   
3  https://api.spotify.com/v1/tracks/1OYOLWqKmhkF...   
4  https://api.spotify.com/v1/tracks/2P8QqrZ42YNP...   

                                        analysis_url duration_ms  \
0  https://api.spotify.com/v1/audio-analysis/1ENn...      247385   
1  https://api.spotify.com/v1/audio-analysis/7ioc...      250573   
2  https://api.spotify.com/v1/audio-analysis/2AIL...      146760   
3  https://api.spotify.com/v1/audio-analysis/1OYO...      214400   
4  https://api.spotify.com/v1/audio-analysis/2P8Q...      115693   

   time_signature  Clusters  
0               4        33  
1               3        25  
2               4         6  
3               3         8  
4               5        29  

[5 rows x 21 columns]

In [35]:
Fs_clu=fs[fs['Clusters']==cluster]

In [36]:
Fs_clu

Song  \
427                      Don't Worry, Be Happy (O.S.T.)   
1855                                                747   
2364                           The Beginning of the End   
2727                                  Changing My Major   
2827  On This Night Of A Thousand Stars / Eva And Ma...   
2866                                      One Last Time   
2888                                    A Little Priest   
3002                                Chip on My Shoulder   
3011                           The Music and the Mirror   
3012                                 Darkness And Trees   
3050                  Any Moment / Moments in the Woods   
3072                                       Take a Break   
3073                                Prologue: Tradition   
3131                               Find My Way / Finale   
3188                                  Board of Govenors   
3243                   Why Are All the D'Ysquiths Dying   
3344                              Look What You've Done   
3348                                    Dear Old Friend   
3352                            (You're) Timeless to Me   
3427                                    Dear Old Friend   
3589                            Forever Yours (Reprise)   
3640                         Foolish to Think - Reprise   

                                                  Movie  \
427       Cocktail (Original Motion Picture Soundtrack)   
1855  Tenet (Original Motion Picture Soundtrack) [De...   
2364                          Requiem for a Dream / OST   
2727                  Fun Home (A New Broadway Musical)   
2827                                              Evita   
2866        Hamilton (Original Broadway Cast Recording)   
2888  Sweeney Todd: The Demon Barber of Fleet Street...   
3002  Legally Blonde The Musical (Original Broadway ...   
3011  A Chorus Line - 40th Anniversary Celebration (...   
3012  Come From Away (Original Broadway Cast Recording)   
3050  Into the Woods (Original Broadway Cast Recording)   
3072        Hamilton (Original Broadway Cast Recording)   
3073  Fiddler on the Roof (Original Broadway Cast Re...   
3131  Legally Blonde The Musical (Original Broadway ...   
3188         Jekyll & Hyde: The Gothic Musical Thriller   
3243  A Gentleman's Guide to Love and Murder (Origin...   
3344  Ragtime: The Musical (Original Broadway Cast R...   
3348                                    Love Never Dies   
3352       Hairspray (Original Broadway Cast Recording)   
3427                                    Love Never Dies   
3589  Once on This Island (Original Broadway Cast Re...   
3640  A Gentleman's Guide to Love and Murder (Origin...   

                                                   Link  \
427   https://api.spotify.com/v1/tracks/1ngmt8WTzBqG...   
1855  https://api.spotify.com/v1/tracks/0v1ZkmgwyRKT...   
2364  https://api.spotify.com/v1/tracks/7CAD3QOpAUwR...   
2727  https://api.spotify.com/v1/tracks/6jgLIGTcVtQl...   
2827  https://api.spotify.com/v1/tracks/5McX7X62MHh4...   
2866  https://api.spotify.com/v1/tracks/0Iys022UwQ8x...   
2888  https://api.spotify.com/v1/tracks/3r0c8sCVp67x...   
3002  https://api.spotify.com/v1/tracks/2UTS33qrSdZU...   
3011  https://api.spotify.com/v1/tracks/4X9Xn0FsKzgq...   
3012  https://api.spotify.com/v1/tracks/27fahUgDyUtR...   
3050  https://api.spotify.com/v1/tracks/5eVCpPA1WwDk...   
3072  https://api.spotify.com/v1/tracks/2qFIJT5hjqaN...   
3073  https://api.spotify.com/v1/tracks/62q1kgVYOG3L...   
3131  https://api.spotify.com/v1/tracks/6Xff7fTzm90x...   
3188  https://api.spotify.com/v1/tracks/0Y2wbYXS9681...   
3243  https://api.spotify.com/v1/tracks/7LSTcTHhzski...   
3344  https://api.spotify.com/v1/tracks/39RfhgCtYH8f...   
3348  https://api.spotify.com/v1/tracks/6fGQkUlcvVsE...   
3352  https://api.spotify.com/v1/tracks/1hgkm8voLNVn...   
3427  https://api.spotify.com/v1/tracks/74r8qu4XjQVf...   
3589  https://api.spotify.com/v1/tracks/5V8pLVXbhN79...   
3640  https://api.spotify.com/v1/trac

In [39]:
import numpy as np
song_rec=Fs_clu[['Song','Movie','Link']].sample().values[0]
print(song_rec)

['Any Moment / Moments in the Woods'
 'Into the Woods (Original Broadway Cast Recording)'
 'https://api.spotify.com/v1/tracks/5eVCpPA1WwDkdgb6BlebV5']


In [46]:
Fs_clu[Fs_clu[['Song','Movie','Link']]==song_rec]['Link']

427                                                   NaN
1855                                                  NaN
2364                                                  NaN
2727                                                  NaN
2827                                                  NaN
2866                                                  NaN
2888                                                  NaN
3002                                                  NaN
3011                                                  NaN
3012                                                  NaN
3050    https://api.spotify.com/v1/tracks/5eVCpPA1WwDk...
3072                                                  NaN
3073                                                  NaN
3131                                                  NaN
3188                                                  NaN
3243                                                  NaN
3344                                                  NaN
3348          

In [40]:
billtops=pd.read_csv('List_songs_artist.csv')

In [41]:
song=input('Enter a song do you like?').title()

KeyboardInterrupt: Interrupted by user

In [ ]:
def song(song=input('Enter a song do you like?').title()):
    
    if song in billtops.Titles.values:
        other= randint(0,(len(billtops)))
        print('Sure you like this:' + '' '' +billtops['Titles'][other] + ' by '+billtops['Artists'][other])
    else:
        results = sp.search(q=song, limit=1)
        id=results["tracks"]['items'][0]['id']
        songf=sp.audio_features(id)
        songf=pd.DataFrame(songf)
        sf_cl=songf.drop(['type','uri','track_href','analysis_url','id'],axis=1)
        scaler= StandardScaler()
        scaler.fit(sf_cl)
        sf_cl_sc=scaler.transform(sf_cl)
        kmeans = KMeans(n_clusters=1, random_state=40)
        kmeans.fit(sf_cl_sc)
        kmeans.cluster_centers_
        cluster=kmeans.predict(sf_cl_sc)
        cluster=cluster[0]
        fs=pd.read_csv('film_series.csv')
        fscl=fs.drop(['Song','Movie','Link','uri','track_href','analysis_url','id'],axis=1)
        scaler.fit(fscl)
        fscl_scl=scaler.transform(fscl)
        kmeans = KMeans(n_clusters=50, random_state=40)
        kmeans.fit(fscl_scl)
        kmeans.cluster_centers_
        clusters=kmeans.predict(fscl_scl)
        fs['Clusters']=clusters
        Fs_clu=fs[fs['Clusters']==cluster]
        song_rec=Fs_clu[['Song','Movie','Link']].sample().values[0]
        song_rec
        return print(song)
    
    

In [ ]:
song